### ISSUE TITLE
Is this demo applicable for both NVP and JSON implementations?

### ISSUE THREAD

**Issue by grifotv** [wirecard/wpp-integration-demo-java#1]

**Comment by horfic** [comment]
Hi,
this demo application is only for json, as its the new recommended format.

cheers

**Comment by grifotv** [comment]
Thanks. Does it use the Signature V1 or Signature V2? Or it's not needed as it's backend-to-backend operation?

**Comment by horfic** [comment]
It is not using signature for request sending, as its a merchant server to wirecard server direct request.

But signature v1 is used for response validation in certain requests

**Comment by grifotv** [comment]
Thanks a lot. Last question: only signature v1 is used for response validation or can signature v2 also be used?

**Comment by horfic** [comment]
The signature v2 is primarly only used for the mobile SDK endpoints, but we offer different response formats with different validation options.

That depends what accept header you are sending.

Possible accept header:
* application/x-www-form-urlencoded
* application/xml
* application/json
* application/json-signed

This can also be set for the notification format

**Comment by grifotv** [comment]
Thanks a lot for this!
